name: Build Lingo Engine APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Unzip Source Code
      run: unzip "lingoengine (1).zip"
      
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Build APK
      run: gradle assembleDebug
      
    - uses: actions/upload-artifact@v3
      with:
        name: Yazen-Lingo-APK
        path: app/build/outputs/apk/debug/app-debug.apk
